import { useState } from 'react';
import { Action, AdaptiveComponent, AdaptiveUIResponse } from './types';
import { FinancialDashboard, GoalDashboard, ActivityList, CashflowAlert } from './DashboardWidgets';
const money = (value: unknown) => `$${Number(value || 0).toLocaleString('es-MX')}`;
type ComponentProps = { component: AdaptiveComponent; onInteract: (component: AdaptiveComponent, action: Action, payload?: Record<string, unknown>) => void };
type RendererProps = { response: AdaptiveUIResponse; onInteract: (component: AdaptiveComponent, action: Action, payload?: Record<string, unknown>) => void };

function Card({ children, className = '' }: { children: React.ReactNode; className?: string }) { return <article className={`data-card ${className}`}>{children}</article>; }
function CardHead({ component }: { component: AdaptiveComponent }) { return <div className="card-head"><div><h2>{component.title}</h2>{component.description && <p>{component.description}</p>}</div><span className="card-index">{component.id.split('-')[0].slice(0, 2).toUpperCase()}</span></div>; }

function Summary({ component }: { component: AdaptiveComponent }) { const d = component.data; return <Card><CardHead component={component}/><div className="summary-main"><div><span>Disponible al mes</span><strong>{money(d.availableMonthlyCash)}</strong></div><div className="balance-bars"><i style={{ width: '59%' }}/><i style={{ width: '16%' }}/><i style={{ width: '25%' }}/></div><div className="summary-legend"><span><i className="income"/>Ingresos {money(d.monthlyIncome)}</span><span><i className="expense"/>Gastos {money(d.monthlyExpenses)}</span><span><i className="saving"/>Ahorro {money(d.currentSavings)}</span></div></div></Card>; }
function Capacity({ component }: { component: AdaptiveComponent }) { const d = component.data; return <Card className="capacity-card"><CardHead component={component}/><div className="capacity-value"><span>Vivienda de hasta</span><strong>{money(d.estimatedPropertyValue)}</strong><em>{String(d.note || '')}</em></div><div className="capacity-foot"><span>Pago mensual estimado <b>{money(d.estimatedMaxPayment)}</b></span><span>Relación de pago <b>{Math.round(Number(d.affordabilityRatio || 0) * 100)}%</b></span></div></Card>; }
function Simulator({ component, onInteract }: ComponentProps) { const d = component.data; const [propertyValue, setPropertyValue] = useState(Number(d.propertyValue)); const [downPayment, setDownPayment] = useState(Number(d.downPayment)); const [termMonths, setTermMonths] = useState(Number(d.termMonths)); return <Card className="simulator-card"><CardHead component={component}/><div className="simulator-layout"><div className="simulator-result"><span>Mensualidad estimada</span><strong>{money(d.estimatedMonthlyPayment)}</strong><small>Tasa anual fija de {String(d.annualRate || 0)}%</small></div><div className="slider-group"><label>Valor de la vivienda <output>{money(propertyValue)}</output></label><input type="range" min="1000000" max="4000000" step="50000" value={propertyValue} onChange={(e) => setPropertyValue(Number(e.target.value))}/><label>Enganche <output>{money(downPayment)}</output></label><input type="range" min="100000" max={Math.max(100000, propertyValue - 100000)} step="10000" value={downPayment} onChange={(e) => setDownPayment(Number(e.target.value))}/><label>Plazo <output>{termMonths / 12} años</output></label><select value={termMonths} onChange={(e) => setTermMonths(Number(e.target.value))}><option value="180">15 años</option><option value="240">20 años</option><option value="300">25 años</option></select></div></div><button className="primary-button" onClick={() => onInteract(component, 'UPDATE_MORTGAGE_SIMULATION', { propertyValue, downPayment, termMonths, productId: d.productId })}>Recalcular escenario <span>{'->'}</span></button></Card>; }
function Products({ component }: { component: AdaptiveComponent }) { const products = Array.isArray(component.data.products) ? component.data.products as Array<Record<string, unknown>> : []; return <Card className="products-card"><CardHead component={component}/><div className="product-grid">{products.map((product) => <div className={`product ${Boolean(product.highlighted) ? 'featured' : ''}`} key={String(product.id)}>{Boolean(product.highlighted) && <span className="featured-label">RECOMENDADO</span>}<h3>{String(product.name)}</h3><p>{String(product.description || '')}</p><strong>{money(product.monthlyPayment)} <small>/ mes</small></strong><div className="product-meta"><span>Tasa <b>{String(product.annualRate)}%</b></span><span>CAT <b>{String(product.cat)}%</b></span></div></div>)}</div></Card>; }
function GoalForm({ component, onInteract }: ComponentProps) { const d = component.data; const [amount, setAmount] = useState(Number(d.targetAmount)); const [monthly, setMonthly] = useState(Number(d.suggestedMonthlyContribution)); return <Card className="goal-card"><CardHead component={component}/><div className="goal-form"><label>¿Cuánto quieres reunir?<output>{money(amount)}</output></label><input type="range" min="20000" max="500000" step="5000" value={amount} onChange={(e) => setAmount(Number(e.target.value))}/><label>Aportación mensual <output>{money(monthly)}</output></label><input type="range" min="1000" max="30000" step="500" value={monthly} onChange={(e) => setMonthly(Number(e.target.value))}/><div className="goal-date"><span>Fecha objetivo</span><b>{new Date(String(d.targetDate)).toLocaleDateString('es-MX', { month: 'long', year: 'numeric' })}</b></div></div><button className="primary-button" onClick={() => onInteract(component, 'REQUEST_CREATE_SAVINGS_GOAL', { targetAmount: amount, monthlyContribution: monthly, targetDate: d.targetDate })}>Continuar con mi meta <span>{'->'}</span></button></Card>; }
function Confirmation({ component, onInteract }: ComponentProps) { const d = component.data; return <Card className="confirmation-card"><div className="confirm-symbol">✓</div><CardHead component={component}/><p className="confirm-message">{String(d.message)}</p><div className="confirm-actions"><button className="primary-button" onClick={() => onInteract(component, 'CONFIRM_CREATE_SAVINGS_GOAL', { targetAmount: d.targetAmount, initialAmount: d.initialAmount, monthlyContribution: d.monthlyContribution, targetDate: d.targetDate })}>{String(d.confirmLabel || 'Confirmar')} <span>{'->'}</span></button><button className="text-button" onClick={() => onInteract(component, 'CANCEL')}>{String(d.cancelLabel || 'Cancelar')}</button></div></Card>; }
function Progress({ component }: { component: AdaptiveComponent }) { const d = component.data; const current = Number(d.currentAmount || 0); const target = Number(d.targetAmount || 1); return <Card className="progress-card"><CardHead component={component}/><div className="progress-number"><strong>{money(current)}</strong><span>de {money(target)}</span></div><div className="progress-track"><i style={{ width: `${Math.min(100, current / target * 100)}%` }}/></div><div className="capacity-foot"><span>Aportación mensual <b>{money(d.monthlyContribution)}</b></span><span>Meta <b>{new Date(String(d.targetDate)).toLocaleDateString('es-MX', { month: 'short', year: 'numeric' })}</b></span></div></Card>; }

export function AdaptiveRenderer({ response, onInteract }: RendererProps) { return <div className="component-stack">{response.components.map((component) => { switch (component.type) { case 'financial-dashboard': return <FinancialDashboard key={component.id} component={component} onInteract={onInteract}/>; case 'goal-dashboard': return <GoalDashboard key={component.id} component={component} onInteract={onInteract}/>; case 'activity-list': return <ActivityList key={component.id} component={component}/>; case 'cashflow-alert': return <CashflowAlert key={component.id} component={component} onInteract={onInteract}/>; case 'credit-options': return <Products key={component.id} component={component}/>; case 'financial-summary': return <Summary key={component.id} component={component}/>; case 'mortgage-capacity': return <Capacity key={component.id} component={component}/>; case 'mortgage-simulator': return <Simulator key={component.id} component={component} onInteract={onInteract}/>; case 'product-comparison': return <Products key={component.id} component={component}/>; case 'savings-goal-form': return <GoalForm key={component.id} component={component} onInteract={onInteract}/>; case 'confirmation': return <Confirmation key={component.id} component={component} onInteract={onInteract}/>; case 'goal-progress': return <Progress key={component.id} component={component}/>; default: return null; } })}</div>; }