import { useState } from 'react';
import { sendInteraction, sendMessage, AuthSession } from './api';
import { AdaptiveUIResponse, Action, AdaptiveComponent } from './types';
import { AdaptiveRenderer } from './AdaptiveRenderer';
import banorteLogo from './public/banorte.png';
import { Login } from './Login';
const suggestions = ['Quiero comprar mi primera casa', 'Quiero empezar a ahorrar', 'Ayúdame a organizar mis finanzas'];
export function App() { const [auth, setAuth] = useState<AuthSession | null>(() => { const saved = sessionStorage.getItem('boreas-auth'); return saved ? JSON.parse(saved) as AuthSession : null; }); const [input, setInput] = useState(''); const [answer, setAnswer] = useState<AdaptiveUIResponse | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [sessionId, setSessionId] = useState(() => sessionStorage.getItem('boreas-session') || undefined); const [history, setHistory] = useState<string[]>([]);
  if (!auth) return <Login onLogin={(session) => { setAuth(session); sessionStorage.setItem('boreas-auth', JSON.stringify(session)); }} />;
  const currentAuth = auth;
  async function submit(message = input) { if (!message.trim() || loading) return; setLoading(true); setError(''); setInput(''); setHistory((current) => [...current, message]); try { const next = await sendMessage({ userId: currentAuth.user.id, message, sessionId }, currentAuth.token); setAnswer(next); setSessionId(next.sessionId); sessionStorage.setItem('boreas-session', next.sessionId); } catch { setError('No pudimos conectar con Boreas. Revisa la conexión e inténtalo de nuevo.'); } finally { setLoading(false); } }
  async function interact(component: AdaptiveComponent, action: Action, payload?: Record<string, unknown>) { if (!sessionId || loading) return; setLoading(true); setError(''); try { const next = await sendInteraction({ userId: currentAuth.user.id, sessionId, componentId: component.id, action, payload }, currentAuth.token); setAnswer(next); } catch { setError('No pudimos actualizar este plan. Inténtalo de nuevo.'); } finally { setLoading(false); } }
  function reset() { setAnswer(null); setHistory([]); setSessionId(undefined); sessionStorage.removeItem('boreas-session'); setError(''); }
  function logout() { reset(); setAuth(null); sessionStorage.removeItem('boreas-auth'); }
  return <div className="app-shell"><header className="topbar"><div className="brand"><img src={banorteLogo} alt="Banorte"/><span className="brand-divider"/><span className="boreas-word">boreas</span></div><div className="topbar-actions"><span className="status-dot">{currentAuth.user.name}</span><button className="icon-button" aria-label="Nueva conversación" onClick={reset}>+</button><button className="logout-button" onClick={logout}>Salir</button><span className="avatar">{currentAuth.user.name.slice(0, 2).toUpperCase()}</span></div></header><main className="main-content"><section className={`hero ${answer ? 'hero-compact' : ''}`}><div className="eyebrow">TU VIDA FINANCIERA, MÁS CLARA <span>///</span></div><h1>{answer ? 'Sigamos construyendo tu siguiente paso.' : '¿Qué quieres lograr hoy?'}</h1><p>{answer ? 'Boreas adapta el camino a lo que necesitas, con números que puedes entender.' : 'Cuéntale a Boreas qué tienes en mente. Nosotros encontramos el camino.'}</p><form className="composer" onSubmit={(event) => { event.preventDefault(); void submit(); }}><input value={input} onChange={(event) => setInput(event.target.value)} placeholder="Ej. Quiero comprar mi primera casa..." aria-label="Escribe tu meta financiera"/><button type="submit" disabled={loading || !input.trim()} aria-label="Enviar mensaje">{loading ? '...' : '->'}</button></form>{!answer && <div className="suggestions">{suggestions.map((item) => <button key={item} onClick={() => void submit(item)}>{item}<span>+</span></button>)}</div>}</section>{error && <div className="error-banner"><span>!</span>{error}<button onClick={() => void submit(history[history.length - 1] || '')}>Reintentar</button></div>}{loading && <div className="loading-state"><div className="loader"/><div><strong>Boreas está pensando contigo</strong><span>Ordenando tus opciones y preparando una vista clara...</span></div></div>}{answer && !loading && <section className="workspace"><div className="conversation-rail"><div className="rail-label">TU CONVERSACIÓN</div>{history.map((item, index) => <div className="history-item" key={`${item}-${index}`}><span>{String(index + 1).padStart(2, '0')}</span>{item}</div>)}<button className="new-conversation" onClick={reset}>+ Nueva conversación</button></div><div className="adaptive-area"><div className="agent-message"><div className="boreas-avatar">B</div><div><span className="agent-label">BOREAS / {answer.intent || 'TU ASISTENTE'}</span><p>{answer.message}</p></div></div><AdaptiveRenderer response={answer} onInteract={interact}/></div></section>}</main><footer><span>Boreas es una experiencia de demostración.</span><span>Las cifras mostradas son estimaciones.</span></footer></div>; }