import { useState } from 'react';
import { Action, AdaptiveComponent } from './types';

const money = (value: unknown) => `$${Number(value || 0).toLocaleString('es-MX', { maximumFractionDigits: 0 })}`;
const date = (value: unknown) => value ? new Date(String(value)).toLocaleDateString('es-MX', { day: 'numeric', month: 'short' }) : 'Hoy';
type Props = { component: AdaptiveComponent; onInteract: (component: AdaptiveComponent, action: Action, payload?: Record<string, unknown>) => void };

export function FinancialDashboard({ component, onInteract }: Props) {
  const data = component.data;
  const [amount, setAmount] = useState('');
  const [type, setType] = useState<'DEPOSIT' | 'EXPENSE' | 'INCOME' | 'WITHDRAWAL'>('DEPOSIT');
  const goals = Array.isArray(data.goals) ? data.goals as Array<Record<string, unknown>> : [];
  const submit = () => { const parsed = Number(amount); if (parsed > 0) { onInteract(component, 'RECORD_FINANCIAL_MOVEMENT', { type, amount: parsed, category: type === 'EXPENSE' ? 'Gasto registrado' : 'Movimiento Boreas', goalId: type === 'DEPOSIT' && goals[0]?.id ? goals[0].id : undefined }); setAmount(''); } };
  return <article className="data-card dashboard-card"><div className="card-head"><div><span className="dashboard-kicker">VISTA GENERAL / ACTUALIZADA</span><h2>{component.title || 'Tu tablero financiero'}</h2><p>Todo lo que cambia tu capacidad de avanzar, en un solo lugar.</p></div><span className="live-badge">EN VIVO</span></div><div className="dashboard-metrics"><div className="metric metric-primary"><span>Disponible estimado</span><strong>{money(data.availableMonthlyCash)}</strong><small>Después de gastos y deuda</small></div><div className="metric"><span>Ingresos</span><strong>{money(data.monthlyIncome)}</strong><small>Base mensual</small></div><div className="metric"><span>Gastos</span><strong>{money(data.monthlyExpenses)}</strong><small>Incluye actividad registrada</small></div><div className="metric"><span>Ahorro líquido</span><strong>{money(data.currentSavings)}</strong><small>Saldo de referencia</small></div></div><div className="dashboard-action"><div><strong>Registrar movimiento</strong><span>Actualiza el tablero y recalcula tu margen.</span></div><select value={type} onChange={(event) => setType(event.target.value as typeof type)}><option value="DEPOSIT">Aportación</option><option value="EXPENSE">Gasto</option><option value="INCOME">Ingreso</option><option value="WITHDRAWAL">Retiro</option></select><input inputMode="decimal" value={amount} onChange={(event) => setAmount(event.target.value)} placeholder="$ Monto" aria-label="Monto del movimiento"/><button className="primary-button" onClick={submit} disabled={!amount}>Registrar <span>{'->'}</span></button></div></article>;
}

export function GoalDashboard({ component, onInteract }: Props) { const goals = Array.isArray(component.data.goals) ? component.data.goals as Array<Record<string, unknown>> : []; return <article className="data-card dashboard-card"><div className="card-head"><div><span className="dashboard-kicker">PLANES / SEGUIMIENTO</span><h2>{component.title || 'Tus metas en marcha'}</h2><p>El avance se actualiza con cada aportación registrada.</p></div><span className="card-index">GO</span></div>{goals.length === 0 ? <div className="empty-dashboard">Aún no tienes metas guardadas. Escribe una meta en el asistente para comenzar.</div> : <div className="goal-dashboard-grid">{goals.map((goal) => { const current = Number(goal.currentAmount || 0); const target = Number(goal.targetAmount || 1); const progress = Math.min(100, current / target * 100); return <div className="goal-mini" key={String(goal.id)}><div className="goal-mini-head"><strong>{String(goal.name)}</strong><span>{Math.round(progress)}%</span></div><div className="progress-track"><i style={{ width: `${progress}%` }}/></div><div className="goal-mini-foot"><span>{money(current)} de {money(target)}</span><button onClick={() => onInteract(component, 'RECORD_FINANCIAL_MOVEMENT', { type: 'DEPOSIT', amount: Number(goal.monthlyContribution) || 0, goalId: goal.id, category: 'Aportación a meta' })}>Aportar {money(goal.monthlyContribution)}</button></div></div>})}</div>}</article>; }

export function ActivityList({ component }: { component: AdaptiveComponent }) { const movements = Array.isArray(component.data.movements) ? component.data.movements as Array<Record<string, unknown>> : []; const labels: Record<string, string> = { DEPOSIT: 'Aportación', EXPENSE: 'Gasto', INCOME: 'Ingreso', WITHDRAWAL: 'Retiro' }; return <article className="data-card activity-card"><div className="card-head"><div><span className="dashboard-kicker">HISTORIAL / ÚLTIMOS MOVIMIENTOS</span><h2>{component.title || 'Actividad reciente'}</h2></div><span className="card-index">{String(movements.length).padStart(2, '0')}</span></div>{movements.length === 0 ? <div className="empty-dashboard">Tus movimientos aparecerán aquí conforme registres actividad.</div> : <div className="activity-list">{movements.map((movement) => <div className="activity-row" key={String(movement.id)}><span className={`activity-icon ${String(movement.type).toLowerCase()}`}>{String(movement.type).slice(0, 1)}</span><div><strong>{labels[String(movement.type)] || String(movement.type)}</strong><small>{String(movement.category || movement.note || 'Movimiento financiero')} · {date(movement.occurredAt)}</small></div><b className={movement.type === 'EXPENSE' || movement.type === 'WITHDRAWAL' ? 'negative' : 'positive'}>{movement.type === 'EXPENSE' || movement.type === 'WITHDRAWAL' ? '-' : '+'}{money(movement.amount)}</b></div>)}</div>}</article>; }

export function CashflowAlert({ component, onInteract }: Props) { return <article className="data-card cashflow-alert"><div className="alert-symbol">!</div><div><span className="dashboard-kicker">IMPACTO PROYECTADO</span><h2>{component.title}</h2><p>{String(component.data.warning || 'Revisa este movimiento antes de continuar.')}</p><div className="alert-numbers"><span>Disponible antes <b>{money(component.data.currentAvailable)}</b></span><span>Después <b>{money(component.data.projectedAvailable)}</b></span></div><button className="primary-button" onClick={() => onInteract(component, 'CONFIRM_RECORD_FINANCIAL_MOVEMENT', component.data.pendingPayload as Record<string, unknown>)}>Confirmar de todos modos <span>{'->'}</span></button></div></article>; }
